version: '3.4'
services:
  app:
    build: .
    container_name: vending_machine
    command: tail -f /dev/null
#    Uncomment on dev
#    volumes:
#      - ./:/srv/app:rw,cached
    networks:
      - vending_machine
    environment:
      - REDIS_HOST=redis_vending_machine
      - REDIS_PORT=6379
  redis:
    container_name: redis_vending_machine
    image: redis
    ports:
      - "6379:6379"
    networks:
      - vending_machine

networks:
  vending_machine:
    driver: bridge
